language: node_js
# 穩定更新版
node_js:
- lts/*

notifications:
  email:
    recipients:
      - god75615@gmail.com
    on_success: always
    on_failure: always

install:
- npm install

script:
- npm run build

# 待補
deploy:
  provider: pages
  github-token: $GITHUB_MOVIE_PROJECT
